# Generated by Django 2.2.5 on 2021-03-16 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(null=True)),
                ('length', models.FloatField(null=True)),
                ('radius', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory_app.Feet')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('leg', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory_app.Leg')),
            ],
        ),
    ]
