# Generated by Django 2.2.5 on 2021-03-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feet',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feet',
            name='radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feet',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
